AWSTemplateFormatVersion: '2010-09-09'
Description: Demo template for testing sceptre hooks
Parameters:
  DomainName:
    Type: String
  SubjectAlternativeNames:
    #Type: CommaDelimitedList
    Type: String
    Default: 'none'
  HostedZoneId:
    Type: String

Conditions:
  SubjectAlternativeNamesEmpty:
    !Equals
      - !Ref SubjectAlternativeNames
      - 'none'


Outputs:
  S3Bucket:
    Description: S3 log bucket for demo stack
    Value: !Ref DemoS3Bucket
  AcmCertificateArn:
    Description: ARN of the generated ACM Certificate
    Value: !Ref DemoCertificate

Resources:
  DemoS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub demo--bucket-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: true

  DemoCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: !Ref DomainName
      DomainValidationOptions: 
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
      SubjectAlternativeNames:
        - !If
          - SubjectAlternativeNamesEmpty
          - !Ref AWS::NoValue
          - !Ref SubjectAlternativeNames
      ValidationMethod: DNS
