template:
  path: demo_template.yaml
  type: file
parameters:
  DomainName: {{ var.domain_name }}
  SubjectAlternativeNames: {{ var.subalt_names | default('!novalue') }}
  HostedZoneId: !hosted_zone_id {{ var.hosted_zone }}

  #hooks:
  #  #before_generate:
  #  before_create:
  #    - !acm_certificate
  #        action: request
  #        cert_fqdn: blee.{{ var.hosted_zone }}
  #        subalt_names: www.blee.{{ var.hosted_zone }},blee00.{{ var.hosted_zone }}
  #        validation_domain: {{ var.hosted_zone }}
  #        region: us-east-1
  #
  #  #before_validate:
  #  before_delete:
  #    - !acm_certificate
  #        action: delete
  #        cert_fqdn: blee.{{ var.hosted_zone }}
  #        validation_domain: {{ var.hosted_zone }}
  #        region: us-east-1

