template:
  path: jinja_demo_template.j2
  type: file
sceptre_user_data:
  domain_name: {{ var.domain_name }}
  hosted_zone_id: !hosted_zone_id {{ var.hosted_zone }}
  subalt_names: {{ var.subalt_names | default('!novalue') }}

  #hooks:
  #  #before_generate:
  #  before_create:
  #    - !acm_certificate
  #        action: request
  #        cert_fqdn: blee.{{ var.hosted_zone }}
  #        subalt_names: www.blee.{{ var.hosted_zone }},blee00.{{ var.hosted_zone }}
  #        validation_domain: {{ var.hosted_zone }}
  #        region: us-east-1
  #
  #  #before_validate:
  #  before_delete:
  #    - !acm_certificate
  #        action: delete
  #        cert_fqdn: blee.{{ var.hosted_zone }}
  #        validation_domain: {{ var.hosted_zone }}
  #        region: us-east-1

